defmodule EventHorizonWeb.Themes do
  @moduledoc """
  Central module for managing website themes.
  Contains all theme definitions and helper functions.
  """

  @themes [
    %{
      id: "default-dark",
      name: "Default",
      background: "#0f0f10",
      accents: ["#21daa2", "#43dce5", "#36c3ef", "#4a5ae9"]
    },
    %{
      id: "vitesse-dark",
      name: "Vitesse",
      background: "#121212",
      accents: ["#7a9f61", "#ba9468", "#7d5750", "#c37272"]
    },
    %{
      id: "gruvbox-dark",
      name: "Gruvbox",
      background: "#1d2021",
      accents: ["#b8bb26", "#8ec07c", "#83a598", "#d3869b"]
    },
    %{
      id: "everforest-dark",
      name: "Everforest",
      background: "#272e33",
      accents: ["#a7c080", "#7fbbb3", "#83c092", "#d699b6"]
    },
    %{
      id: "nature",
      name: "Nature",
      background: "#141a15",
      accents: ["#7caa43", "#8fb286", "#5a8d7d", "#a68c6e"]
    },
    %{
      id: "rosepine-dark",
      name: "Rosé Pine",
      background: "#191724",
      accents: ["#f6c177", "#9ccfd8", "#31748f", "#c4a7e7"]
    }
  ]

  @doc """
  Returns the list of theme metadata for UI rendering.
  """
  def list_themes, do: @themes

  @doc """
  Returns the CSS variables map for a given theme id.
  """
  def get_theme("default-dark"), do: default_dark()
  def get_theme("vitesse-dark"), do: vitesse_dark()
  def get_theme("gruvbox-dark"), do: gruvbox_dark()
  def get_theme("everforest-dark"), do: everforest_dark()
  def get_theme("nature"), do: nature()
  def get_theme("rosepine-dark"), do: rosepine_dark()
  def get_theme(_), do: default_dark()

  @doc """
  Returns all themes with their CSS variables for embedding in the page.
  """
  def themes_with_variables do
    Enum.map(@themes, fn theme ->
      Map.put(theme, :variables, get_theme(theme.id))
    end)
  end

  # Default Dark Theme
  defp default_dark do
    %{
      "--background" => "#101114",
      "--text-color" => "#fff",
      "--link-hover" => "#fff",
      "--link-color" => "#53bcf0",
      "--li-marker" => "#5686f5",
      "--home-next-steps-background" => "#0a0a0a",
      "--code-background" => "#4d4d4d4d",
      "--view-all-background" => "#191919",
      "--view-all-background-hover" => "#252525",
      "--projects-paragraph" => "#919191",
      "--project-box-background" => "#0a0a0a",
      "--books-paragraph" => "#919191",
      "--blog-reading-time" => "gray",
      "--blog-no-of-blogs" => "#919191",
      "--blog-container-hover" => "#191919",
      "--blog-container-focus" => "rgb(236, 236, 236)",
      "--blog-category-btn-bg" => "#191919",
      "--blog-category-btn-color" => "#eee",
      "--blog-category-btn-hover-bg" => "#252525",
      "--blog-category-btn-active-bg" => "#2a2a2a",
      "--blog-category-btn-active-color" => "#fff",
      "--blog-tag-bg" => "#191919",
      "--blog-tag-color" => "#eee",
      "--blog-tag-border" => "#2a2a2a",
      "--blog-tag-hover-bg" => "#252525",
      "--blog-tag-hover-border" => "#3a3a3a",
      "--blog-tag-selected-bg" => "#eee",
      "--blog-tag-selected-color" => "#101114",
      "--blog-tag-selected-border" => "#eee",
      "--blog-search-header-color" => "#fff",
      "--blog-no-blogs-color" => "#919191",
      "--details-background" => "#22272a",
      "--details-focus" => "#22272a",
      "--summary-color" => "white",
      "--summary-list-color" => "white",
      "--tags-background" => "#191919",
      "--tags-color" => "#eee",
      "--tag-selected" => "#191919",
      "--tag-selected-background" => "#eee",
      "--input-container-background" => "rgb(34, 34, 34)",
      "--container-svg-color" => "gray",
      "--input-color" => "white",
      "--other-color" => "gray",
      "--next-prev-info-color" => "gray",
      "--next-prev-container-hover" => "#191919",
      "--blog-span-info" => "white",
      "--blog-description" => "gray",
      "--blog-container-title" => "white",
      "--blog-other-info-color" => "gray",
      "--blog-caption" => "gray",
      "--blog-caption-link" => "white",
      "--blog-content-color" => "rgba(255, 255, 255, 0.74)",
      "--like-button" => "#fff",
      "--like-button-hover" => "rgb(199, 73, 73)",
      "--blog-information" => "white",
      "--blog-headers" => "white",
      "--blog-headers-link" => "rgb(83, 188, 240)",
      "--blog-text-color" => "rgba(255, 255, 255, 0.74)",
      "--blockquote-background" => "#0a0a0a",
      "--blockquote-color" => "white",
      "--header-separator-color" => "gray",
      "--other-separator-color" => "#569cd6",
      "--callout-icon-green" => "#56f58b",
      "--callout-background-green" => "#1d3329",
      "--callout-icon-red" => "#fa4e4e",
      "--callout-background-red" => "#472027",
      "--callout-color" => "black",
      "--card-background" => "#131417",
      "--card-border" => "#252932",
      "--code-filename-color" => "white",
      "--code-filename-container" => "#181818",
      "--codeblock-background" => "#2e2e2e",
      "--hidden-expand-background" => "#2e2e2e63",
      "--hidden-expand-color" => "white",
      "--ol-ul-marker" => "rgb(86, 134, 245)",
      "--anchor-color" => "rgb(83, 188, 240)",
      "--theme-one" => "#21daa2",
      "--theme-two" => "#43dce5",
      "--theme-three" => "#36c3ef",
      "--theme-four" => "#4a5ae9",
      "--nav-links-color" => "#999999",
      "--nav-link-active" => "white",
      "--nav-link-container-color" => "white",
      "--kbar-click" => "#fff",
      "--kbar-command" => "#fff",
      "--footer-border-top" => "rgb(27, 27, 27)",
      "--footer-background" => "#0a0a0a",
      "--footer-color" => "gray",
      "--footer-color-hover" => "white",
      "--footer-content-bg" => "rgba(10, 10, 10, 0.8)",
      "--cloud-color-1" => "#21daa2",
      "--cloud-color-2" => "#43dce5",
      "--cloud-color-3" => "#36c3ef",
      "--cloud-color-4" => "#4a5ae9",
      "--users-online-circle" => "#43dce5",
      "--spotify-container-background" => "rgba(0, 0, 0, 0.2)",
      "--spotify-container-hover" => "rgba(0, 0, 0, 0.324)",
      "--spotify-title" => "white",
      "--code-text" => "#d4d4d4",
      "--code-bg" => "#1e1e1e",
      "--code-selection-bg" => "#264f78",
      "--comment-color" => "#6a9955",
      "--string-color" => "#ce9178",
      "--number-color" => "#b5cea8",
      "--keyword-color" => "#569cd6",
      "--keyword-control-color" => "#c586c0",
      "--function-color" => "#dcdcaa",
      "--class-color" => "#4ec9b0",
      "--variable-color" => "#9cdcfe",
      "--punctuation-color" => "#d4d4d4",
      "--tag-color" => "#569cd6",
      "--tag-punctuation" => "#808080",
      "--attr-name-color" => "#9cdcfe",
      "--attr-value-color" => "#ce9178",
      "--regex-color" => "#d16969",
      "--highlight-bg" => "rgba(55, 65, 81, 0.5)",
      "--highlight-border" => "rgb(59, 130, 246)",
      "--line-number-color" => "rgb(107, 107, 107)",
      "--inserted-line-bg" => "rgba(16, 185, 129, 0.2)",
      "--deleted-line-bg" => "rgba(239, 68, 68, 0.2)"
    }
  end

  # Vitesse Dark Theme
  defp vitesse_dark do
    %{
      "--background" => "#121212",
      "--text-color" => "#c3bfb3",
      "--link-hover" => "#ba9468",
      "--link-color" => "#4c9173",
      "--li-marker" => "#c37272",
      "--home-next-steps-background" => "#0a0a0a",
      "--code-background" => "#4d4d4d4d",
      "--view-all-background" => "#191919",
      "--view-all-background-hover" => "#252525",
      "--projects-paragraph" => "#919191",
      "--project-box-background" => "#0a0a0a",
      "--books-paragraph" => "#919191",
      "--blog-reading-time" => "gray",
      "--blog-no-of-blogs" => "#919191",
      "--blog-container-hover" => "#191919",
      "--blog-container-focus" => "rgb(236, 236, 236)",
      "--blog-category-btn-bg" => "#191919",
      "--blog-category-btn-color" => "#eee",
      "--blog-category-btn-hover-bg" => "#252525",
      "--blog-category-btn-active-bg" => "#2a2a2a",
      "--blog-category-btn-active-color" => "#fff",
      "--blog-tag-bg" => "#191919",
      "--blog-tag-color" => "#eee",
      "--blog-tag-border" => "#2a2a2a",
      "--blog-tag-hover-bg" => "#252525",
      "--blog-tag-hover-border" => "#3a3a3a",
      "--blog-tag-selected-bg" => "#7d5750",
      "--blog-tag-selected-color" => "#fff",
      "--blog-tag-selected-border" => "#7d5750",
      "--blog-search-header-color" => "#c3bfb3",
      "--blog-no-blogs-color" => "#919191",
      "--details-background" => "#22272a",
      "--details-focus" => "#22272a",
      "--summary-color" => "white",
      "--summary-list-color" => "#7a9f61",
      "--tags-background" => "#191919",
      "--tags-color" => "#eee",
      "--tag-selected" => "#fff",
      "--tag-selected-background" => "#7d5750",
      "--input-container-background" => "rgb(34, 34, 34)",
      "--container-svg-color" => "gray",
      "--input-color" => "white",
      "--other-color" => "gray",
      "--header-separator-color" => "gray",
      "--other-separator-color" => "#569cd6",
      "--next-prev-info-color" => "gray",
      "--next-prev-container-hover" => "#191919",
      "--blog-description" => "white",
      "--blog-container-title" => "white",
      "--blog-other-info-color" => "gray",
      "--blog-caption" => "gray",
      "--blog-caption-link" => "white",
      "--blog-content-color" => "rgba(255, 255, 255, 0.74)",
      "--like-button" => "#fff",
      "--like-button-hover" => "rgb(199, 73, 73)",
      "--blog-span-info" => "white",
      "--blog-information" => "white",
      "--blog-headers" => "white",
      "--blog-text-color" => "rgba(255, 255, 255, 0.74)",
      "--blog-headers-link" => "#7a9f61",
      "--blockquote-background" => "#0a0a0a",
      "--blockquote-color" => "white",
      "--callout-icon-green" => "#56f58b",
      "--callout-background-green" => "#1d3329",
      "--callout-icon-red" => "#fa4e4e",
      "--callout-background-red" => "#472027",
      "--callout-color" => "black",
      "--card-background" => "#121212cf",
      "--card-border" => "rgb(27, 27, 27)",
      "--code-filename-color" => "white",
      "--code-filename-container" => "#181818",
      "--codeblock-background" => "#2e2e2e",
      "--hidden-expand-background" => "#2e2e2e63",
      "--hidden-expand-color" => "white",
      "--ol-ul-marker" => "#c37272",
      "--anchor-color" => "#7d5750",
      "--theme-one" => "#7a9f61",
      "--theme-two" => "#ba9468",
      "--theme-three" => "#7d5750",
      "--theme-four" => "#c37272",
      "--nav-links-color" => "#999999",
      "--nav-link-active" => "#ba9468",
      "--nav-link-container-color" => "#ba9468",
      "--kbar-click" => "#fff",
      "--kbar-command" => "#fff",
      "--footer-border-top" => "rgb(27, 27, 27)",
      "--footer-background" => "#0a0a0a",
      "--footer-color" => "gray",
      "--footer-color-hover" => "white",
      "--footer-content-bg" => "rgba(10, 10, 10, 0.8)",
      "--cloud-color-1" => "#7a9f61",
      "--cloud-color-2" => "#ba9468",
      "--cloud-color-3" => "#7d5750",
      "--cloud-color-4" => "#c37272",
      "--users-online-circle" => "#7a9f61",
      "--spotify-container-background" => "rgba(0, 0, 0, 0.2)",
      "--spotify-container-hover" => "rgba(0, 0, 0, 0.324)",
      "--spotify-title" => "white",
      "--code-text" => "#d4d4d4",
      "--code-bg" => "#1e1e1e",
      "--code-selection-bg" => "#264f78",
      "--comment-color" => "#6a9955",
      "--string-color" => "#ce9178",
      "--number-color" => "#b5cea8",
      "--keyword-color" => "#569cd6",
      "--keyword-control-color" => "#c586c0",
      "--function-color" => "#dcdcaa",
      "--class-color" => "#4ec9b0",
      "--variable-color" => "#9cdcfe",
      "--punctuation-color" => "#d4d4d4",
      "--tag-color" => "#569cd6",
      "--tag-punctuation" => "#808080",
      "--attr-name-color" => "#9cdcfe",
      "--attr-value-color" => "#ce9178",
      "--regex-color" => "#d16969",
      "--highlight-bg" => "rgba(55, 65, 81, 0.5)",
      "--highlight-border" => "rgb(59, 130, 246)",
      "--line-number-color" => "rgb(107, 107, 107)",
      "--inserted-line-bg" => "rgba(16, 185, 129, 0.2)",
      "--deleted-line-bg" => "rgba(239, 68, 68, 0.2)"
    }
  end

  # Gruvbox Dark Theme
  defp gruvbox_dark do
    %{
      "--background" => "#1d2021",
      "--text-color" => "#ebdbb2",
      "--link-hover" => "#8ec07c",
      "--link-color" => "#4c9173",
      "--li-marker" => "#c37272",
      "--home-next-steps-background" => "#282828",
      "--code-background" => "#4d4d4d4d",
      "--view-all-background" => "#3c3836",
      "--view-all-background-hover" => "#3c3836",
      "--projects-paragraph" => "#919191",
      "--project-box-background" => "#282828",
      "--books-paragraph" => "#919191",
      "--blog-reading-time" => "gray",
      "--blog-no-of-blogs" => "#919191",
      "--blog-container-hover" => "#282828",
      "--blog-container-focus" => "#fbf1c7",
      "--blog-category-btn-bg" => "#3c3836",
      "--blog-category-btn-color" => "#fbf1c7",
      "--blog-category-btn-hover-bg" => "#504945",
      "--blog-category-btn-active-bg" => "#665c54",
      "--blog-category-btn-active-color" => "#fbf1c7",
      "--blog-tag-bg" => "#3c3836",
      "--blog-tag-color" => "#fbf1c7",
      "--blog-tag-border" => "#504945",
      "--blog-tag-hover-bg" => "#504945",
      "--blog-tag-hover-border" => "#665c54",
      "--blog-tag-selected-bg" => "#7d5750",
      "--blog-tag-selected-color" => "#fff",
      "--blog-tag-selected-border" => "#7d5750",
      "--blog-search-header-color" => "#ebdbb2",
      "--blog-no-blogs-color" => "#919191",
      "--details-background" => "#22272a",
      "--details-focus" => "#22272a",
      "--summary-color" => "#ebdbb2",
      "--summary-list-color" => "#7a9f61",
      "--tags-background" => "#191919",
      "--tags-color" => "#fbf1c7",
      "--tag-selected" => "#fff",
      "--tag-selected-background" => "#7d5750",
      "--input-container-background" => "rgb(34, 34, 34)",
      "--container-svg-color" => "gray",
      "--input-color" => "white",
      "--other-color" => "gray",
      "--next-prev-info-color" => "gray",
      "--next-prev-container-hover" => "#191919",
      "--blog-container-title" => "white",
      "--blog-other-info-color" => "gray",
      "--blog-caption" => "gray",
      "--blog-caption-link" => "white",
      "--blog-content-color" => "rgba(255, 255, 255, 0.74)",
      "--blog-text-color" => "#ebdbb2",
      "--like-button" => "#fff",
      "--like-button-hover" => "rgb(199, 73, 73)",
      "--blog-span-info" => "#ebdbb2",
      "--blog-information" => "red",
      "--blog-headers" => "#ebdbb2",
      "--blog-description" => "#ebdbb2",
      "--blog-headers-link" => "#7a9f61",
      "--blockquote-background" => "#282828",
      "--blockquote-color" => "white",
      "--header-separator-color" => "#b8bb26",
      "--other-separator-color" => "#83a598",
      "--callout-icon-green" => "#8ec07c",
      "--callout-background-green" => "#689d6a",
      "--callout-icon-red" => "#cc241d",
      "--callout-background-red" => "#fb4934",
      "--callout-color" => "black",
      "--card-background" => "#282828",
      "--card-border" => "#928374",
      "--code-filename-color" => "white",
      "--code-filename-container" => "#181818",
      "--codeblock-background" => "#32302f",
      "--hidden-expand-background" => "#2e2e2e63",
      "--hidden-expand-color" => "white",
      "--ol-ul-marker" => "#c37272",
      "--anchor-color" => "#7d5750",
      "--theme-one" => "#b8bb26",
      "--theme-two" => "#8ec07c",
      "--theme-three" => "#83a598",
      "--theme-four" => "#d3869b",
      "--nav-links-color" => "#999999",
      "--nav-link-active" => "#8ec07c",
      "--nav-link-container-color" => "#8ec07c",
      "--kbar-click" => "#fff",
      "--kbar-command" => "#fff",
      "--footer-border-top" => "rgb(27, 27, 27)",
      "--footer-background" => "#282828",
      "--footer-color" => "gray",
      "--footer-color-hover" => "#b8bb26",
      "--footer-content-bg" => "rgba(40, 40, 40, 0.8)",
      "--cloud-color-1" => "#b8bb26",
      "--cloud-color-2" => "#8ec07c",
      "--cloud-color-3" => "#83a598",
      "--cloud-color-4" => "#d3869b",
      "--users-online-circle" => "#7a9f61",
      "--spotify-container-background" => "rgba(0, 0, 0, 0.2)",
      "--spotify-container-hover" => "rgba(0, 0, 0, 0.324)",
      "--spotify-title" => "white",
      "--code-text" => "#d4d4d4",
      "--code-bg" => "#1e1e1e",
      "--code-selection-bg" => "#264f78",
      "--comment-color" => "#6a9955",
      "--string-color" => "#ce9178",
      "--number-color" => "#b5cea8",
      "--keyword-color" => "#569cd6",
      "--keyword-control-color" => "#c586c0",
      "--function-color" => "#dcdcaa",
      "--class-color" => "#4ec9b0",
      "--variable-color" => "#9cdcfe",
      "--punctuation-color" => "#d4d4d4",
      "--tag-color" => "#569cd6",
      "--tag-punctuation" => "#808080",
      "--attr-name-color" => "#9cdcfe",
      "--attr-value-color" => "#ce9178",
      "--regex-color" => "#d16969",
      "--highlight-bg" => "rgba(55, 65, 81, 0.5)",
      "--highlight-border" => "rgb(59, 130, 246)",
      "--line-number-color" => "rgb(107, 107, 107)",
      "--inserted-line-bg" => "rgba(16, 185, 129, 0.2)",
      "--deleted-line-bg" => "rgba(239, 68, 68, 0.2)"
    }
  end

  # Everforest Dark Theme
  defp everforest_dark do
    %{
      "--background" => "#272e33",
      "--text-color" => "#d3c6aa",
      "--link-hover" => "#8ec07c",
      "--link-color" => "#4c9173",
      "--li-marker" => "#c37272",
      "--home-next-steps-background" => "#282828",
      "--code-background" => "#4d4d4d4d",
      "--view-all-background" => "#3c3836",
      "--view-all-background-hover" => "#3c3836",
      "--projects-paragraph" => "#919191",
      "--project-box-background" => "#282828",
      "--books-paragraph" => "#919191",
      "--blog-reading-time" => "gray",
      "--blog-no-of-blogs" => "#919191",
      "--blog-container-hover" => "#282828",
      "--blog-container-focus" => "#fbf1c7",
      "--blog-category-btn-bg" => "#3c3836",
      "--blog-category-btn-color" => "#d3c6aa",
      "--blog-category-btn-hover-bg" => "#504945",
      "--blog-category-btn-active-bg" => "#665c54",
      "--blog-category-btn-active-color" => "#d3c6aa",
      "--blog-tag-bg" => "#3c3836",
      "--blog-tag-color" => "#d3c6aa",
      "--blog-tag-border" => "#504945",
      "--blog-tag-hover-bg" => "#504945",
      "--blog-tag-hover-border" => "#665c54",
      "--blog-tag-selected-bg" => "#7d5750",
      "--blog-tag-selected-color" => "#fff",
      "--blog-tag-selected-border" => "#7d5750",
      "--blog-search-header-color" => "#d3c6aa",
      "--blog-no-blogs-color" => "#919191",
      "--details-background" => "#22272a",
      "--details-focus" => "#22272a",
      "--summary-color" => "#ebdbb2",
      "--summary-list-color" => "#7a9f61",
      "--tags-background" => "#191919",
      "--tags-color" => "#fbf1c7",
      "--tag-selected" => "#fff",
      "--tag-selected-background" => "#7d5750",
      "--input-container-background" => "rgb(34, 34, 34)",
      "--container-svg-color" => "gray",
      "--input-color" => "white",
      "--other-color" => "gray",
      "--next-prev-info-color" => "gray",
      "--next-prev-container-hover" => "#191919",
      "--blog-container-title" => "white",
      "--blog-other-info-color" => "gray",
      "--blog-caption" => "gray",
      "--blog-caption-link" => "white",
      "--blog-content-color" => "rgba(255, 255, 255, 0.74)",
      "--blog-text-color" => "#ebdbb2",
      "--like-button" => "#fff",
      "--like-button-hover" => "rgb(199, 73, 73)",
      "--blog-span-info" => "#ebdbb2",
      "--blog-information" => "red",
      "--blog-headers" => "#ebdbb2",
      "--blog-description" => "#ebdbb2",
      "--blog-headers-link" => "#7a9f61",
      "--blockquote-background" => "#282828",
      "--blockquote-color" => "white",
      "--header-separator-color" => "#b8bb26",
      "--other-separator-color" => "#83a598",
      "--callout-icon-green" => "#8ec07c",
      "--callout-background-green" => "#689d6a",
      "--callout-icon-red" => "#cc241d",
      "--callout-background-red" => "#fb4934",
      "--callout-color" => "black",
      "--card-background" => "#282828",
      "--card-border" => "#928374",
      "--code-filename-color" => "white",
      "--code-filename-container" => "#181818",
      "--codeblock-background" => "#32302f",
      "--hidden-expand-background" => "#2e2e2e63",
      "--hidden-expand-color" => "white",
      "--ol-ul-marker" => "#c37272",
      "--anchor-color" => "#7d5750",
      "--theme-one" => "#a7c080",
      "--theme-two" => "#7fbbb3",
      "--theme-three" => "#83c092",
      "--theme-four" => "#d699b6",
      "--nav-links-color" => "#999999",
      "--nav-link-active" => "#8ec07c",
      "--nav-link-container-color" => "#8ec07c",
      "--kbar-click" => "#fff",
      "--kbar-command" => "#fff",
      "--footer-border-top" => "rgb(27, 27, 27)",
      "--footer-background" => "#282828",
      "--footer-color" => "gray",
      "--footer-color-hover" => "#b8bb26",
      "--footer-content-bg" => "rgba(40, 40, 40, 0.8)",
      "--cloud-color-1" => "#a7c080",
      "--cloud-color-2" => "#7fbbb3",
      "--cloud-color-3" => "#83c092",
      "--cloud-color-4" => "#d699b6",
      "--users-online-circle" => "#7a9f61",
      "--spotify-container-background" => "rgba(0, 0, 0, 0.2)",
      "--spotify-container-hover" => "rgba(0, 0, 0, 0.324)",
      "--spotify-title" => "white",
      "--code-text" => "#d4d4d4",
      "--code-bg" => "#1e1e1e",
      "--code-selection-bg" => "#264f78",
      "--comment-color" => "#6a9955",
      "--string-color" => "#ce9178",
      "--number-color" => "#b5cea8",
      "--keyword-color" => "#569cd6",
      "--keyword-control-color" => "#c586c0",
      "--function-color" => "#dcdcaa",
      "--class-color" => "#4ec9b0",
      "--variable-color" => "#9cdcfe",
      "--punctuation-color" => "#d4d4d4",
      "--tag-color" => "#569cd6",
      "--tag-punctuation" => "#808080",
      "--attr-name-color" => "#9cdcfe",
      "--attr-value-color" => "#ce9178",
      "--regex-color" => "#d16969",
      "--highlight-bg" => "rgba(55, 65, 81, 0.5)",
      "--highlight-border" => "rgb(59, 130, 246)",
      "--line-number-color" => "rgb(107, 107, 107)",
      "--inserted-line-bg" => "rgba(16, 185, 129, 0.2)",
      "--deleted-line-bg" => "rgba(239, 68, 68, 0.2)"
    }
  end

  # Nature Theme
  defp nature do
    %{
      "--background" => "#141a15",
      "--text-color" => "#d2e3c8",
      "--link-hover" => "#8fb286",
      "--link-color" => "#6b9c63",
      "--li-marker" => "#7a9e7a",
      "--home-next-steps-background" => "#1c261d",
      "--code-background" => "#2c3c2a4d",
      "--view-all-background" => "#1e2a1f",
      "--view-all-background-hover" => "#243024",
      "--projects-paragraph" => "#a0b4a0",
      "--project-box-background" => "#1c261d",
      "--books-paragraph" => "#a0b4a0",
      "--blog-reading-time" => "#91aa90",
      "--blog-no-of-blogs" => "#a0b4a0",
      "--blog-container-hover" => "#1c261d",
      "--blog-container-focus" => "#2a382b",
      "--blog-category-btn-bg" => "#1e2a1f",
      "--blog-category-btn-color" => "#d2e3c8",
      "--blog-category-btn-hover-bg" => "#243024",
      "--blog-category-btn-active-bg" => "#2a382b",
      "--blog-category-btn-active-color" => "#d2e3c8",
      "--blog-tag-bg" => "#1e2a1f",
      "--blog-tag-color" => "#d2e3c8",
      "--blog-tag-border" => "#243024",
      "--blog-tag-hover-bg" => "#243024",
      "--blog-tag-hover-border" => "#2a382b",
      "--blog-tag-selected-bg" => "#7a9e7a",
      "--blog-tag-selected-color" => "#141a15",
      "--blog-tag-selected-border" => "#7a9e7a",
      "--blog-search-header-color" => "#d2e3c8",
      "--blog-no-blogs-color" => "#a0b4a0",
      "--blog-container-title" => "#d2e3c8",
      "--blog-other-info-color" => "#a0b4a0",
      "--blog-caption" => "#a0b4a0",
      "--blog-caption-link" => "#8fb286",
      "--blog-content-color" => "rgba(210, 227, 200, 0.85)",
      "--blog-text-color" => "#d2e3c8",
      "--blog-span-info" => "#d2e3c8",
      "--blog-information" => "#d08569",
      "--blog-headers" => "#d2e3c8",
      "--blog-description" => "#d2e3c8",
      "--blog-headers-link" => "#8fb286",
      "--details-background" => "#1e2a1f",
      "--details-focus" => "#243024",
      "--summary-color" => "#d2e3c8",
      "--summary-list-color" => "#8fb286",
      "--tags-background" => "#1c261d",
      "--tags-color" => "#d2e3c8",
      "--tag-selected" => "#141a15",
      "--tag-selected-background" => "#7a9e7a",
      "--input-container-background" => "#1e2a1f",
      "--container-svg-color" => "#a0b4a0",
      "--input-color" => "#d2e3c8",
      "--other-color" => "#a0b4a0",
      "--next-prev-info-color" => "#a0b4a0",
      "--next-prev-container-hover" => "#1e2a1f",
      "--like-button" => "#d2e3c8",
      "--like-button-hover" => "#d08569",
      "--blockquote-background" => "#1e2a1f",
      "--blockquote-color" => "#d2e3c8",
      "--header-separator-color" => "#7caa43",
      "--other-separator-color" => "#5a8d7d",
      "--callout-icon-green" => "#8fb286",
      "--callout-background-green" => "#2c3c2a",
      "--callout-icon-red" => "#d08569",
      "--callout-background-red" => "#3c291f",
      "--callout-color" => "#d2e3c8",
      "--card-background" => "#1c261d",
      "--card-border" => "#2e3c2e",
      "--code-filename-color" => "#d2e3c8",
      "--code-filename-container" => "#243024",
      "--codeblock-background" => "#1e2a1f",
      "--hidden-expand-background" => "#24302480",
      "--hidden-expand-color" => "#d2e3c8",
      "--ol-ul-marker" => "#7a9e7a",
      "--anchor-color" => "#7a9e7a",
      "--theme-one" => "#7caa43",
      "--theme-two" => "#8fb286",
      "--theme-three" => "#5a8d7d",
      "--theme-four" => "#a68c6e",
      "--nav-links-color" => "#a0b4a0",
      "--nav-link-active" => "#8fb286",
      "--nav-link-container-color" => "#8fb286",
      "--kbar-click" => "#d2e3c8",
      "--kbar-command" => "#d2e3c8",
      "--footer-border-top" => "#1c261d",
      "--footer-background" => "#1c261d",
      "--footer-color" => "#a0b4a0",
      "--footer-color-hover" => "#7caa43",
      "--footer-content-bg" => "rgba(28, 38, 29, 0.8)",
      "--cloud-color-1" => "#7caa43",
      "--cloud-color-2" => "#8fb286",
      "--cloud-color-3" => "#5a8d7d",
      "--cloud-color-4" => "#a68c6e",
      "--users-online-circle" => "#8fb286",
      "--spotify-container-background" => "rgba(30, 42, 31, 0.7)",
      "--spotify-container-hover" => "rgba(36, 48, 36, 0.8)",
      "--spotify-title" => "#d2e3c8",
      "--code-text" => "#d4d4d4",
      "--code-bg" => "#1e1e1e",
      "--code-selection-bg" => "#264f78",
      "--comment-color" => "#6a9955",
      "--string-color" => "#ce9178",
      "--number-color" => "#b5cea8",
      "--keyword-color" => "#569cd6",
      "--keyword-control-color" => "#c586c0",
      "--function-color" => "#dcdcaa",
      "--class-color" => "#4ec9b0",
      "--variable-color" => "#9cdcfe",
      "--punctuation-color" => "#d4d4d4",
      "--tag-color" => "#569cd6",
      "--tag-punctuation" => "#808080",
      "--attr-name-color" => "#9cdcfe",
      "--attr-value-color" => "#ce9178",
      "--regex-color" => "#d16969",
      "--highlight-bg" => "rgba(55, 65, 81, 0.5)",
      "--highlight-border" => "rgb(59, 130, 246)",
      "--line-number-color" => "rgb(107, 107, 107)",
      "--inserted-line-bg" => "rgba(16, 185, 129, 0.2)",
      "--deleted-line-bg" => "rgba(239, 68, 68, 0.2)"
    }
  end

  # Rosé Pine Dark Theme
  defp rosepine_dark do
    %{
      "--background" => "#191724",
      "--text-color" => "#e0def4",
      "--link-hover" => "#9ccfd8",
      "--link-color" => "#31748f",
      "--li-marker" => "#eb6f92",
      "--home-next-steps-background" => "#1f1d2e",
      "--code-background" => "#26233a4d",
      "--view-all-background" => "#26233a",
      "--view-all-background-hover" => "#26233a",
      "--projects-paragraph" => "#908caa",
      "--project-box-background" => "#1f1d2e",
      "--books-paragraph" => "#908caa",
      "--blog-reading-time" => "#6e6a86",
      "--blog-no-of-blogs" => "#908caa",
      "--blog-container-hover" => "#1f1d2e",
      "--blog-container-focus" => "#e0def4",
      "--blog-category-btn-bg" => "#26233a",
      "--blog-category-btn-color" => "#e0def4",
      "--blog-category-btn-hover-bg" => "#403d52",
      "--blog-category-btn-active-bg" => "#524f67",
      "--blog-category-btn-active-color" => "#e0def4",
      "--blog-tag-bg" => "#26233a",
      "--blog-tag-color" => "#e0def4",
      "--blog-tag-border" => "#403d52",
      "--blog-tag-hover-bg" => "#403d52",
      "--blog-tag-hover-border" => "#524f67",
      "--blog-tag-selected-bg" => "#eb6f92",
      "--blog-tag-selected-color" => "#e0def4",
      "--blog-tag-selected-border" => "#eb6f92",
      "--blog-search-header-color" => "#e0def4",
      "--blog-no-blogs-color" => "#908caa",
      "--details-background" => "#21202e",
      "--details-focus" => "#21202e",
      "--summary-color" => "#e0def4",
      "--summary-list-color" => "#c4a7e7",
      "--tags-background" => "#191724",
      "--tags-color" => "#e0def4",
      "--tag-selected" => "#e0def4",
      "--tag-selected-background" => "#eb6f92",
      "--input-container-background" => "#1f1d2e",
      "--container-svg-color" => "#6e6a86",
      "--input-color" => "#e0def4",
      "--other-color" => "#6e6a86",
      "--next-prev-info-color" => "#6e6a86",
      "--next-prev-container-hover" => "#191724",
      "--blog-container-title" => "#e0def4",
      "--blog-other-info-color" => "#6e6a86",
      "--blog-caption" => "#6e6a86",
      "--blog-caption-link" => "#e0def4",
      "--blog-content-color" => "rgba(224, 222, 244, 0.74)",
      "--blog-text-color" => "#e0def4",
      "--like-button" => "#e0def4",
      "--like-button-hover" => "#eb6f92",
      "--blog-span-info" => "#e0def4",
      "--blog-information" => "#eb6f92",
      "--blog-headers" => "#e0def4",
      "--blog-description" => "#e0def4",
      "--blog-headers-link" => "#c4a7e7",
      "--blockquote-background" => "#1f1d2e",
      "--blockquote-color" => "#e0def4",
      "--header-separator-color" => "#f6c177",
      "--other-separator-color" => "#9ccfd8",
      "--callout-icon-green" => "#9ccfd8",
      "--callout-background-green" => "#31748f",
      "--callout-icon-red" => "#eb6f92",
      "--callout-background-red" => "#eb6f92",
      "--callout-color" => "#191724",
      "--card-background" => "#1f1d2e",
      "--card-border" => "#6e6a86",
      "--code-filename-color" => "#e0def4",
      "--code-filename-container" => "#191724",
      "--codeblock-background" => "#26233a",
      "--hidden-expand-background" => "#403d5263",
      "--hidden-expand-color" => "#e0def4",
      "--ol-ul-marker" => "#eb6f92",
      "--anchor-color" => "#eb6f92",
      "--theme-one" => "#f6c177",
      "--theme-two" => "#9ccfd8",
      "--theme-three" => "#31748f",
      "--theme-four" => "#c4a7e7",
      "--nav-links-color" => "#6e6a86",
      "--nav-link-active" => "#9ccfd8",
      "--nav-link-container-color" => "#9ccfd8",
      "--kbar-click" => "#e0def4",
      "--kbar-command" => "#e0def4",
      "--footer-border-top" => "#21202e",
      "--footer-background" => "#1f1d2e",
      "--footer-color" => "#6e6a86",
      "--footer-color-hover" => "#f6c177",
      "--footer-content-bg" => "rgba(31, 29, 46, 0.8)",
      "--cloud-color-1" => "#f6c177",
      "--cloud-color-2" => "#9ccfd8",
      "--cloud-color-3" => "#31748f",
      "--cloud-color-4" => "#c4a7e7",
      "--users-online-circle" => "#c4a7e7",
      "--spotify-container-background" => "rgba(25, 23, 36, 0.2)",
      "--spotify-container-hover" => "rgba(25, 23, 36, 0.324)",
      "--spotify-title" => "#e0def4",
      "--code-text" => "#e0def4",
      "--code-bg" => "#191724",
      "--code-selection-bg" => "#403d52",
      "--comment-color" => "#6e6a86",
      "--string-color" => "#ebbcba",
      "--number-color" => "#f6c177",
      "--keyword-color" => "#31748f",
      "--keyword-control-color" => "#c4a7e7",
      "--function-color" => "#9ccfd8",
      "--class-color" => "#9ccfd8",
      "--variable-color" => "#e0def4",
      "--punctuation-color" => "#908caa",
      "--tag-color" => "#31748f",
      "--tag-punctuation" => "#6e6a86",
      "--attr-name-color" => "#ebbcba",
      "--attr-value-color" => "#f6c177",
      "--regex-color" => "#eb6f92",
      "--highlight-bg" => "rgba(38, 35, 58, 0.5)",
      "--highlight-border" => "#c4a7e7",
      "--line-number-color" => "#6e6a86",
      "--inserted-line-bg" => "rgba(156, 207, 216, 0.2)",
      "--deleted-line-bg" => "rgba(235, 111, 146, 0.2)"
    }
  end
end
